/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result, EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export type ListingStruct = {
  status: BigNumberish;
  seller: string;
  price: BigNumberish;
  token: string;
  tokenId: BigNumberish;
  startListingUTC: BigNumberish;
  tokenPaymentsAmount: BigNumberish;
  cashback: BigNumberish;
  isTokenFee: boolean;
};

export type ListingStructOutput = [
  number,
  string,
  BigNumber,
  string,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  boolean
] & {
  status: number;
  seller: string;
  price: BigNumber;
  token: string;
  tokenId: BigNumber;
  startListingUTC: BigNumber;
  tokenPaymentsAmount: BigNumber;
  cashback: BigNumber;
  isTokenFee: boolean;
};

export type StakingStruct = {
  status: BigNumberish;
  maker: string;
  taker: string;
  collateral: BigNumberish;
  premium: BigNumberish;
  startRentalUTC: BigNumberish;
  startStakingUTC: BigNumberish;
  paymentsAmount: BigNumberish;
  tokenPaymentsAmount: BigNumberish;
  deadline: BigNumberish;
  token: string;
  tokenId: BigNumberish;
};

export type StakingStructOutput = [
  number,
  string,
  string,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  string,
  BigNumber
] & {
  status: number;
  maker: string;
  taker: string;
  collateral: BigNumber;
  premium: BigNumber;
  startRentalUTC: BigNumber;
  startStakingUTC: BigNumber;
  paymentsAmount: BigNumber;
  tokenPaymentsAmount: BigNumber;
  deadline: BigNumber;
  token: string;
  tokenId: BigNumber;
};

export interface MarketplaceInterface extends utils.Interface {
  functions: {
    "NFTTokenDistributionWhiteLister()": FunctionFragment;
    "NFTsEligibleForTokenDistribution(address)": FunctionFragment;
    "_listings(uint256)": FunctionFragment;
    "_listingsLastIndex()": FunctionFragment;
    "_offerLastIndex()": FunctionFragment;
    "_stakings(uint256)": FunctionFragment;
    "_stakingsExtension(uint256)": FunctionFragment;
    "_stakingsLastIndex()": FunctionFragment;
    "acceptListingOffer(uint256,address)": FunctionFragment;
    "acceptOfferForNotListedToken(uint256,address)": FunctionFragment;
    "acceptStakingOffer(uint256,address,bool)": FunctionFragment;
    "bidAndStake(address,uint256,uint256,uint256,uint256,uint256,bool)": FunctionFragment;
    "bidExternal(address,uint256,uint256,bool)": FunctionFragment;
    "buyToken(uint256)": FunctionFragment;
    "canRentNFT(uint256)": FunctionFragment;
    "cancel(uint256)": FunctionFragment;
    "cancelListingOffer(uint256)": FunctionFragment;
    "cancelOfferForNotListedToken(uint256)": FunctionFragment;
    "cancelStakingOffer(uint256)": FunctionFragment;
    "claimCollateral(uint256)": FunctionFragment;
    "claimTokensListing(uint256)": FunctionFragment;
    "claimTokensRent(uint256)": FunctionFragment;
    "dateOfNextPayment(uint256)": FunctionFragment;
    "denyOfferForNotListedToken(uint256)": FunctionFragment;
    "factory()": FunctionFragment;
    "getContractBalanceV2()": FunctionFragment;
    "getListing(uint256)": FunctionFragment;
    "getStaking(uint256)": FunctionFragment;
    "initialize(address,address,address,uint256,uint256,address,address)": FunctionFragment;
    "isBuyable(uint256)": FunctionFragment;
    "isCollateralClaimable(uint256)": FunctionFragment;
    "listingOffer(uint256)": FunctionFragment;
    "maxCollateralEligibleForTokens()": FunctionFragment;
    "nftListingIds(address,uint256)": FunctionFragment;
    "nftStakingIds(address,uint256)": FunctionFragment;
    "offerForNotListedToken(uint256,uint256,address)": FunctionFragment;
    "payPremium(uint256,bool)": FunctionFragment;
    "paymentsDue(uint256)": FunctionFragment;
    "platform()": FunctionFragment;
    "quoteForStakingExternal(address,uint256,uint256,uint256,uint256,bool)": FunctionFragment;
    "removeStakingOffer(uint256)": FunctionFragment;
    "rentNFT(uint256,bool)": FunctionFragment;
    "stakingOffer(uint256,uint256,uint256)": FunctionFragment;
    "stopRental(uint256)": FunctionFragment;
    "stopStaking(uint256)": FunctionFragment;
    "tokensDistributionAmount()": FunctionFragment;
    "tokensDistributionEnd()": FunctionFragment;
    "undasToken()": FunctionFragment;
    "wETH()": FunctionFragment;
    "whiteListNFTToggle(address,bool)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "NFTTokenDistributionWhiteLister",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "NFTsEligibleForTokenDistribution",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "_listings",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "_listingsLastIndex",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "_offerLastIndex",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "_stakings",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "_stakingsExtension",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "_stakingsLastIndex",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "acceptListingOffer",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "acceptOfferForNotListedToken",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "acceptStakingOffer",
    values: [BigNumberish, string, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "bidAndStake",
    values: [
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      boolean
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "bidExternal",
    values: [string, BigNumberish, BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "buyToken",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "canRentNFT",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cancel",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelListingOffer",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelOfferForNotListedToken",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelStakingOffer",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimCollateral",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimTokensListing",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimTokensRent",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "dateOfNextPayment",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "denyOfferForNotListedToken",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "factory", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getContractBalanceV2",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getListing",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getStaking",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [string, string, string, BigNumberish, BigNumberish, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "isBuyable",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isCollateralClaimable",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "listingOffer",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "maxCollateralEligibleForTokens",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "nftListingIds",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "nftStakingIds",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "offerForNotListedToken",
    values: [BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "payPremium",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "paymentsDue",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "platform", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "quoteForStakingExternal",
    values: [
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      boolean
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "removeStakingOffer",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "rentNFT",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "stakingOffer",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "stopRental",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "stopStaking",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "tokensDistributionAmount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "tokensDistributionEnd",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "undasToken",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "wETH", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "whiteListNFTToggle",
    values: [string, boolean]
  ): string;

  decodeFunctionResult(
    functionFragment: "NFTTokenDistributionWhiteLister",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "NFTsEligibleForTokenDistribution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "_listings", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "_listingsLastIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_offerLastIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "_stakings", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "_stakingsExtension",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_stakingsLastIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "acceptListingOffer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "acceptOfferForNotListedToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "acceptStakingOffer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "bidAndStake",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "bidExternal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "buyToken", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "canRentNFT", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "cancel", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "cancelListingOffer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelOfferForNotListedToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelStakingOffer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimCollateral",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimTokensListing",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimTokensRent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "dateOfNextPayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "denyOfferForNotListedToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "factory", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getContractBalanceV2",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getListing", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getStaking", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isBuyable", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isCollateralClaimable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "listingOffer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxCollateralEligibleForTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nftListingIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nftStakingIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "offerForNotListedToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "payPremium", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "paymentsDue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "platform", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "quoteForStakingExternal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeStakingOffer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "rentNFT", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "stakingOffer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "stopRental", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "stopStaking",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tokensDistributionAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tokensDistributionEnd",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "undasToken", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "wETH", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "whiteListNFTToggle",
    data: BytesLike
  ): Result;

  events: {
    "CancelBid(uint256,address)": EventFragment;
    "CancelStaking(uint256)": EventFragment;
    "FinishRentalForCollateral(uint256)": EventFragment;
    "FinishRentalForNFT(uint256)": EventFragment;
    "Initialized(uint8)": EventFragment;
    "Listed(uint256,address,address,uint256,uint256)": EventFragment;
    "ListingOffer(uint256,address,uint256)": EventFragment;
    "ListingOfferCompleted(uint256,address)": EventFragment;
    "OfferForNotListed(uint8,uint256,uint256,uint256,uint256,address)": EventFragment;
    "QuotedForStaking(uint256,address,address,uint256,uint256,uint256,uint256)": EventFragment;
    "Rental(uint256,address)": EventFragment;
    "Sale(uint256,address,address,uint256,uint256)": EventFragment;
    "StakingOfferAccepted(uint256,address)": EventFragment;
    "StakingOffered(uint256,address,uint256,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "CancelBid"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "CancelStaking"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "FinishRentalForCollateral"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "FinishRentalForNFT"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Initialized"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Listed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ListingOffer"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ListingOfferCompleted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OfferForNotListed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "QuotedForStaking"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Rental"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Sale"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "StakingOfferAccepted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "StakingOffered"): EventFragment;
}

export type CancelBidEvent = TypedEvent<
  [BigNumber, string],
  { listingId: BigNumber; seller: string }
>;

export type CancelBidEventFilter = TypedEventFilter<CancelBidEvent>;

export type CancelStakingEvent = TypedEvent<
  [BigNumber],
  { stakingId: BigNumber }
>;

export type CancelStakingEventFilter = TypedEventFilter<CancelStakingEvent>;

export type FinishRentalForCollateralEvent = TypedEvent<
  [BigNumber],
  { rentalId: BigNumber }
>;

export type FinishRentalForCollateralEventFilter =
  TypedEventFilter<FinishRentalForCollateralEvent>;

export type FinishRentalForNFTEvent = TypedEvent<
  [BigNumber],
  { rentalId: BigNumber }
>;

export type FinishRentalForNFTEventFilter =
  TypedEventFilter<FinishRentalForNFTEvent>;

export type InitializedEvent = TypedEvent<[number], { version: number }>;

export type InitializedEventFilter = TypedEventFilter<InitializedEvent>;

export type ListedEvent = TypedEvent<
  [BigNumber, string, string, BigNumber, BigNumber],
  {
    listingId: BigNumber;
    seller: string;
    token: string;
    tokenId: BigNumber;
    price: BigNumber;
  }
>;

export type ListedEventFilter = TypedEventFilter<ListedEvent>;

export type ListingOfferEvent = TypedEvent<
  [BigNumber, string, BigNumber],
  { listingId: BigNumber; buyer: string; amount: BigNumber }
>;

export type ListingOfferEventFilter = TypedEventFilter<ListingOfferEvent>;

export type ListingOfferCompletedEvent = TypedEvent<
  [BigNumber, string],
  { listingId: BigNumber; buyer: string }
>;

export type ListingOfferCompletedEventFilter =
  TypedEventFilter<ListingOfferCompletedEvent>;

export type OfferForNotListedEvent = TypedEvent<
  [number, BigNumber, BigNumber, BigNumber, BigNumber, string],
  {
    status: number;
    offerId: BigNumber;
    tokenId: BigNumber;
    collectionId: BigNumber;
    amount: BigNumber;
    actor: string;
  }
>;

export type OfferForNotListedEventFilter =
  TypedEventFilter<OfferForNotListedEvent>;

export type QuotedForStakingEvent = TypedEvent<
  [BigNumber, string, string, BigNumber, BigNumber, BigNumber, BigNumber],
  {
    stakingId: BigNumber;
    maker: string;
    token: string;
    tokenId: BigNumber;
    collateral: BigNumber;
    premium: BigNumber;
    deadline: BigNumber;
  }
>;

export type QuotedForStakingEventFilter =
  TypedEventFilter<QuotedForStakingEvent>;

export type RentalEvent = TypedEvent<
  [BigNumber, string],
  { rentalId: BigNumber; taker: string }
>;

export type RentalEventFilter = TypedEventFilter<RentalEvent>;

export type SaleEvent = TypedEvent<
  [BigNumber, string, string, BigNumber, BigNumber],
  {
    listingId: BigNumber;
    buyer: string;
    token: string;
    tokenId: BigNumber;
    price: BigNumber;
  }
>;

export type SaleEventFilter = TypedEventFilter<SaleEvent>;

export type StakingOfferAcceptedEvent = TypedEvent<
  [BigNumber, string],
  { stakingId: BigNumber; taker: string }
>;

export type StakingOfferAcceptedEventFilter =
  TypedEventFilter<StakingOfferAcceptedEvent>;

export type StakingOfferedEvent = TypedEvent<
  [BigNumber, string, BigNumber, BigNumber],
  {
    stakingId: BigNumber;
    taker: string;
    collateral: BigNumber;
    premium: BigNumber;
  }
>;

export type StakingOfferedEventFilter = TypedEventFilter<StakingOfferedEvent>;

export interface Marketplace extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: MarketplaceInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    NFTTokenDistributionWhiteLister(
      overrides?: CallOverrides
    ): Promise<[string]>;

    NFTsEligibleForTokenDistribution(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    _listings(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        number,
        string,
        BigNumber,
        string,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        boolean
      ] & {
        status: number;
        seller: string;
        price: BigNumber;
        token: string;
        tokenId: BigNumber;
        startListingUTC: BigNumber;
        tokenPaymentsAmount: BigNumber;
        cashback: BigNumber;
        isTokenFee: boolean;
      }
    >;

    _listingsLastIndex(overrides?: CallOverrides): Promise<[BigNumber]>;

    _offerLastIndex(overrides?: CallOverrides): Promise<[BigNumber]>;

    _stakings(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        number,
        string,
        string,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        string,
        BigNumber
      ] & {
        status: number;
        maker: string;
        taker: string;
        collateral: BigNumber;
        premium: BigNumber;
        startRentalUTC: BigNumber;
        startStakingUTC: BigNumber;
        paymentsAmount: BigNumber;
        tokenPaymentsAmount: BigNumber;
        deadline: BigNumber;
        token: string;
        tokenId: BigNumber;
      }
    >;

    _stakingsExtension(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, boolean] & { cashback: BigNumber; isTokenFee: boolean }
    >;

    _stakingsLastIndex(overrides?: CallOverrides): Promise<[BigNumber]>;

    acceptListingOffer(
      listingId: BigNumberish,
      taker: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    acceptOfferForNotListedToken(
      offerId: BigNumberish,
      tokenContract: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    acceptStakingOffer(
      stakingId: BigNumberish,
      taker: string,
      isTokenFee: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    bidAndStake(
      tokenContract: string,
      tokenId: BigNumberish,
      collateralWei: BigNumberish,
      premiumWei: BigNumberish,
      deadlineUTC: BigNumberish,
      priceWei: BigNumberish,
      isTokenFee: boolean,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    bidExternal(
      tokenContract: string,
      tokenId: BigNumberish,
      priceWei: BigNumberish,
      isTokenFee: boolean,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    buyToken(
      listingId: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    canRentNFT(
      stakingId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    cancel(
      listingId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    cancelListingOffer(
      listingId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    cancelOfferForNotListedToken(
      offerId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    cancelStakingOffer(
      listingId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    claimCollateral(
      stakingId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    claimTokensListing(
      id: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    claimTokensRent(
      id: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    dateOfNextPayment(
      stakingId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { date: BigNumber }>;

    denyOfferForNotListedToken(
      offerId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    factory(overrides?: CallOverrides): Promise<[string]>;

    getContractBalanceV2(overrides?: CallOverrides): Promise<[BigNumber]>;

    getListing(
      listingId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[ListingStructOutput]>;

    getStaking(
      stakingId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[StakingStructOutput]>;

    initialize(
      _platform: string,
      _token: string,
      _NFTTokenDistributionWhiteLister: string,
      _tokensDistributionAmount: BigNumberish,
      _maxCollateralEligibleForTokens: BigNumberish,
      _factory: string,
      _wETH: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    isBuyable(
      listingId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    isCollateralClaimable(
      stakingId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean] & { status: boolean }>;

    listingOffer(
      listingId: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    maxCollateralEligibleForTokens(
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    nftListingIds(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [boolean, BigNumber] & { valueExists: boolean; value: BigNumber }
    >;

    nftStakingIds(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [boolean, BigNumber] & { valueExists: boolean; value: BigNumber }
    >;

    offerForNotListedToken(
      collectionId: BigNumberish,
      tokenId: BigNumberish,
      tokenContract: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    payPremium(
      stakingId: BigNumberish,
      isToken: boolean,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    paymentsDue(
      stakingId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { amountDue: BigNumber }>;

    platform(overrides?: CallOverrides): Promise<[string]>;

    quoteForStakingExternal(
      tokenContract: string,
      tokenId: BigNumberish,
      collateralWei: BigNumberish,
      premiumWei: BigNumberish,
      deadlineUTC: BigNumberish,
      isTokenFee: boolean,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    removeStakingOffer(
      stakingId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    rentNFT(
      stakingId: BigNumberish,
      isTokenFee: boolean,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    stakingOffer(
      stakingId: BigNumberish,
      _collateral: BigNumberish,
      _premium: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    stopRental(
      stakingId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    stopStaking(
      stakingIndex: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    tokensDistributionAmount(overrides?: CallOverrides): Promise<[BigNumber]>;

    tokensDistributionEnd(overrides?: CallOverrides): Promise<[BigNumber]>;

    undasToken(overrides?: CallOverrides): Promise<[string]>;

    wETH(overrides?: CallOverrides): Promise<[string]>;

    whiteListNFTToggle(
      nft: string,
      whitelist: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  NFTTokenDistributionWhiteLister(overrides?: CallOverrides): Promise<string>;

  NFTsEligibleForTokenDistribution(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  _listings(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [
      number,
      string,
      BigNumber,
      string,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      boolean
    ] & {
      status: number;
      seller: string;
      price: BigNumber;
      token: string;
      tokenId: BigNumber;
      startListingUTC: BigNumber;
      tokenPaymentsAmount: BigNumber;
      cashback: BigNumber;
      isTokenFee: boolean;
    }
  >;

  _listingsLastIndex(overrides?: CallOverrides): Promise<BigNumber>;

  _offerLastIndex(overrides?: CallOverrides): Promise<BigNumber>;

  _stakings(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [
      number,
      string,
      string,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      string,
      BigNumber
    ] & {
      status: number;
      maker: string;
      taker: string;
      collateral: BigNumber;
      premium: BigNumber;
      startRentalUTC: BigNumber;
      startStakingUTC: BigNumber;
      paymentsAmount: BigNumber;
      tokenPaymentsAmount: BigNumber;
      deadline: BigNumber;
      token: string;
      tokenId: BigNumber;
    }
  >;

  _stakingsExtension(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, boolean] & { cashback: BigNumber; isTokenFee: boolean }
  >;

  _stakingsLastIndex(overrides?: CallOverrides): Promise<BigNumber>;

  acceptListingOffer(
    listingId: BigNumberish,
    taker: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  acceptOfferForNotListedToken(
    offerId: BigNumberish,
    tokenContract: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  acceptStakingOffer(
    stakingId: BigNumberish,
    taker: string,
    isTokenFee: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  bidAndStake(
    tokenContract: string,
    tokenId: BigNumberish,
    collateralWei: BigNumberish,
    premiumWei: BigNumberish,
    deadlineUTC: BigNumberish,
    priceWei: BigNumberish,
    isTokenFee: boolean,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  bidExternal(
    tokenContract: string,
    tokenId: BigNumberish,
    priceWei: BigNumberish,
    isTokenFee: boolean,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  buyToken(
    listingId: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  canRentNFT(
    stakingId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  cancel(
    listingId: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  cancelListingOffer(
    listingId: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  cancelOfferForNotListedToken(
    offerId: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  cancelStakingOffer(
    listingId: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  claimCollateral(
    stakingId: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  claimTokensListing(
    id: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  claimTokensRent(
    id: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  dateOfNextPayment(
    stakingId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  denyOfferForNotListedToken(
    offerId: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  factory(overrides?: CallOverrides): Promise<string>;

  getContractBalanceV2(overrides?: CallOverrides): Promise<BigNumber>;

  getListing(
    listingId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<ListingStructOutput>;

  getStaking(
    stakingId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<StakingStructOutput>;

  initialize(
    _platform: string,
    _token: string,
    _NFTTokenDistributionWhiteLister: string,
    _tokensDistributionAmount: BigNumberish,
    _maxCollateralEligibleForTokens: BigNumberish,
    _factory: string,
    _wETH: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  isBuyable(
    listingId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  isCollateralClaimable(
    stakingId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  listingOffer(
    listingId: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  maxCollateralEligibleForTokens(overrides?: CallOverrides): Promise<BigNumber>;

  nftListingIds(
    arg0: string,
    arg1: BigNumberish,
    overrides?: CallOverrides
  ): Promise<[boolean, BigNumber] & { valueExists: boolean; value: BigNumber }>;

  nftStakingIds(
    arg0: string,
    arg1: BigNumberish,
    overrides?: CallOverrides
  ): Promise<[boolean, BigNumber] & { valueExists: boolean; value: BigNumber }>;

  offerForNotListedToken(
    collectionId: BigNumberish,
    tokenId: BigNumberish,
    tokenContract: string,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  payPremium(
    stakingId: BigNumberish,
    isToken: boolean,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  paymentsDue(
    stakingId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  platform(overrides?: CallOverrides): Promise<string>;

  quoteForStakingExternal(
    tokenContract: string,
    tokenId: BigNumberish,
    collateralWei: BigNumberish,
    premiumWei: BigNumberish,
    deadlineUTC: BigNumberish,
    isTokenFee: boolean,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  removeStakingOffer(
    stakingId: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  rentNFT(
    stakingId: BigNumberish,
    isTokenFee: boolean,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  stakingOffer(
    stakingId: BigNumberish,
    _collateral: BigNumberish,
    _premium: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  stopRental(
    stakingId: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  stopStaking(
    stakingIndex: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  tokensDistributionAmount(overrides?: CallOverrides): Promise<BigNumber>;

  tokensDistributionEnd(overrides?: CallOverrides): Promise<BigNumber>;

  undasToken(overrides?: CallOverrides): Promise<string>;

  wETH(overrides?: CallOverrides): Promise<string>;

  whiteListNFTToggle(
    nft: string,
    whitelist: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    NFTTokenDistributionWhiteLister(overrides?: CallOverrides): Promise<string>;

    NFTsEligibleForTokenDistribution(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    _listings(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        number,
        string,
        BigNumber,
        string,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        boolean
      ] & {
        status: number;
        seller: string;
        price: BigNumber;
        token: string;
        tokenId: BigNumber;
        startListingUTC: BigNumber;
        tokenPaymentsAmount: BigNumber;
        cashback: BigNumber;
        isTokenFee: boolean;
      }
    >;

    _listingsLastIndex(overrides?: CallOverrides): Promise<BigNumber>;

    _offerLastIndex(overrides?: CallOverrides): Promise<BigNumber>;

    _stakings(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        number,
        string,
        string,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        string,
        BigNumber
      ] & {
        status: number;
        maker: string;
        taker: string;
        collateral: BigNumber;
        premium: BigNumber;
        startRentalUTC: BigNumber;
        startStakingUTC: BigNumber;
        paymentsAmount: BigNumber;
        tokenPaymentsAmount: BigNumber;
        deadline: BigNumber;
        token: string;
        tokenId: BigNumber;
      }
    >;

    _stakingsExtension(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, boolean] & { cashback: BigNumber; isTokenFee: boolean }
    >;

    _stakingsLastIndex(overrides?: CallOverrides): Promise<BigNumber>;

    acceptListingOffer(
      listingId: BigNumberish,
      taker: string,
      overrides?: CallOverrides
    ): Promise<void>;

    acceptOfferForNotListedToken(
      offerId: BigNumberish,
      tokenContract: string,
      overrides?: CallOverrides
    ): Promise<void>;

    acceptStakingOffer(
      stakingId: BigNumberish,
      taker: string,
      isTokenFee: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    bidAndStake(
      tokenContract: string,
      tokenId: BigNumberish,
      collateralWei: BigNumberish,
      premiumWei: BigNumberish,
      deadlineUTC: BigNumberish,
      priceWei: BigNumberish,
      isTokenFee: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    bidExternal(
      tokenContract: string,
      tokenId: BigNumberish,
      priceWei: BigNumberish,
      isTokenFee: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    buyToken(listingId: BigNumberish, overrides?: CallOverrides): Promise<void>;

    canRentNFT(
      stakingId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    cancel(listingId: BigNumberish, overrides?: CallOverrides): Promise<void>;

    cancelListingOffer(
      listingId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    cancelOfferForNotListedToken(
      offerId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    cancelStakingOffer(
      listingId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    claimCollateral(
      stakingId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    claimTokensListing(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    claimTokensRent(id: BigNumberish, overrides?: CallOverrides): Promise<void>;

    dateOfNextPayment(
      stakingId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    denyOfferForNotListedToken(
      offerId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    factory(overrides?: CallOverrides): Promise<string>;

    getContractBalanceV2(overrides?: CallOverrides): Promise<BigNumber>;

    getListing(
      listingId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<ListingStructOutput>;

    getStaking(
      stakingId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<StakingStructOutput>;

    initialize(
      _platform: string,
      _token: string,
      _NFTTokenDistributionWhiteLister: string,
      _tokensDistributionAmount: BigNumberish,
      _maxCollateralEligibleForTokens: BigNumberish,
      _factory: string,
      _wETH: string,
      overrides?: CallOverrides
    ): Promise<void>;

    isBuyable(
      listingId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    isCollateralClaimable(
      stakingId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    listingOffer(
      listingId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    maxCollateralEligibleForTokens(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    nftListingIds(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [boolean, BigNumber] & { valueExists: boolean; value: BigNumber }
    >;

    nftStakingIds(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [boolean, BigNumber] & { valueExists: boolean; value: BigNumber }
    >;

    offerForNotListedToken(
      collectionId: BigNumberish,
      tokenId: BigNumberish,
      tokenContract: string,
      overrides?: CallOverrides
    ): Promise<void>;

    payPremium(
      stakingId: BigNumberish,
      isToken: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    paymentsDue(
      stakingId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    platform(overrides?: CallOverrides): Promise<string>;

    quoteForStakingExternal(
      tokenContract: string,
      tokenId: BigNumberish,
      collateralWei: BigNumberish,
      premiumWei: BigNumberish,
      deadlineUTC: BigNumberish,
      isTokenFee: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    removeStakingOffer(
      stakingId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    rentNFT(
      stakingId: BigNumberish,
      isTokenFee: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    stakingOffer(
      stakingId: BigNumberish,
      _collateral: BigNumberish,
      _premium: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    stopRental(
      stakingId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    stopStaking(
      stakingIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    tokensDistributionAmount(overrides?: CallOverrides): Promise<BigNumber>;

    tokensDistributionEnd(overrides?: CallOverrides): Promise<BigNumber>;

    undasToken(overrides?: CallOverrides): Promise<string>;

    wETH(overrides?: CallOverrides): Promise<string>;

    whiteListNFTToggle(
      nft: string,
      whitelist: boolean,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "CancelBid(uint256,address)"(
      listingId?: null,
      seller?: null
    ): CancelBidEventFilter;
    CancelBid(listingId?: null, seller?: null): CancelBidEventFilter;

    "CancelStaking(uint256)"(stakingId?: null): CancelStakingEventFilter;
    CancelStaking(stakingId?: null): CancelStakingEventFilter;

    "FinishRentalForCollateral(uint256)"(
      rentalId?: null
    ): FinishRentalForCollateralEventFilter;
    FinishRentalForCollateral(
      rentalId?: null
    ): FinishRentalForCollateralEventFilter;

    "FinishRentalForNFT(uint256)"(
      rentalId?: null
    ): FinishRentalForNFTEventFilter;
    FinishRentalForNFT(rentalId?: null): FinishRentalForNFTEventFilter;

    "Initialized(uint8)"(version?: null): InitializedEventFilter;
    Initialized(version?: null): InitializedEventFilter;

    "Listed(uint256,address,address,uint256,uint256)"(
      listingId?: null,
      seller?: null,
      token?: null,
      tokenId?: null,
      price?: null
    ): ListedEventFilter;
    Listed(
      listingId?: null,
      seller?: null,
      token?: null,
      tokenId?: null,
      price?: null
    ): ListedEventFilter;

    "ListingOffer(uint256,address,uint256)"(
      listingId?: null,
      buyer?: null,
      amount?: null
    ): ListingOfferEventFilter;
    ListingOffer(
      listingId?: null,
      buyer?: null,
      amount?: null
    ): ListingOfferEventFilter;

    "ListingOfferCompleted(uint256,address)"(
      listingId?: null,
      buyer?: null
    ): ListingOfferCompletedEventFilter;
    ListingOfferCompleted(
      listingId?: null,
      buyer?: null
    ): ListingOfferCompletedEventFilter;

    "OfferForNotListed(uint8,uint256,uint256,uint256,uint256,address)"(
      status?: null,
      offerId?: null,
      tokenId?: null,
      collectionId?: null,
      amount?: null,
      actor?: null
    ): OfferForNotListedEventFilter;
    OfferForNotListed(
      status?: null,
      offerId?: null,
      tokenId?: null,
      collectionId?: null,
      amount?: null,
      actor?: null
    ): OfferForNotListedEventFilter;

    "QuotedForStaking(uint256,address,address,uint256,uint256,uint256,uint256)"(
      stakingId?: null,
      maker?: null,
      token?: null,
      tokenId?: null,
      collateral?: null,
      premium?: null,
      deadline?: null
    ): QuotedForStakingEventFilter;
    QuotedForStaking(
      stakingId?: null,
      maker?: null,
      token?: null,
      tokenId?: null,
      collateral?: null,
      premium?: null,
      deadline?: null
    ): QuotedForStakingEventFilter;

    "Rental(uint256,address)"(rentalId?: null, taker?: null): RentalEventFilter;
    Rental(rentalId?: null, taker?: null): RentalEventFilter;

    "Sale(uint256,address,address,uint256,uint256)"(
      listingId?: null,
      buyer?: null,
      token?: null,
      tokenId?: null,
      price?: null
    ): SaleEventFilter;
    Sale(
      listingId?: null,
      buyer?: null,
      token?: null,
      tokenId?: null,
      price?: null
    ): SaleEventFilter;

    "StakingOfferAccepted(uint256,address)"(
      stakingId?: null,
      taker?: null
    ): StakingOfferAcceptedEventFilter;
    StakingOfferAccepted(
      stakingId?: null,
      taker?: null
    ): StakingOfferAcceptedEventFilter;

    "StakingOffered(uint256,address,uint256,uint256)"(
      stakingId?: null,
      taker?: null,
      collateral?: null,
      premium?: null
    ): StakingOfferedEventFilter;
    StakingOffered(
      stakingId?: null,
      taker?: null,
      collateral?: null,
      premium?: null
    ): StakingOfferedEventFilter;
  };

  estimateGas: {
    NFTTokenDistributionWhiteLister(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    NFTsEligibleForTokenDistribution(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    _listings(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    _listingsLastIndex(overrides?: CallOverrides): Promise<BigNumber>;

    _offerLastIndex(overrides?: CallOverrides): Promise<BigNumber>;

    _stakings(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    _stakingsExtension(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    _stakingsLastIndex(overrides?: CallOverrides): Promise<BigNumber>;

    acceptListingOffer(
      listingId: BigNumberish,
      taker: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    acceptOfferForNotListedToken(
      offerId: BigNumberish,
      tokenContract: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    acceptStakingOffer(
      stakingId: BigNumberish,
      taker: string,
      isTokenFee: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    bidAndStake(
      tokenContract: string,
      tokenId: BigNumberish,
      collateralWei: BigNumberish,
      premiumWei: BigNumberish,
      deadlineUTC: BigNumberish,
      priceWei: BigNumberish,
      isTokenFee: boolean,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    bidExternal(
      tokenContract: string,
      tokenId: BigNumberish,
      priceWei: BigNumberish,
      isTokenFee: boolean,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    buyToken(
      listingId: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    canRentNFT(
      stakingId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    cancel(
      listingId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    cancelListingOffer(
      listingId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    cancelOfferForNotListedToken(
      offerId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    cancelStakingOffer(
      listingId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    claimCollateral(
      stakingId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    claimTokensListing(
      id: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    claimTokensRent(
      id: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    dateOfNextPayment(
      stakingId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    denyOfferForNotListedToken(
      offerId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    factory(overrides?: CallOverrides): Promise<BigNumber>;

    getContractBalanceV2(overrides?: CallOverrides): Promise<BigNumber>;

    getListing(
      listingId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getStaking(
      stakingId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    initialize(
      _platform: string,
      _token: string,
      _NFTTokenDistributionWhiteLister: string,
      _tokensDistributionAmount: BigNumberish,
      _maxCollateralEligibleForTokens: BigNumberish,
      _factory: string,
      _wETH: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    isBuyable(
      listingId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isCollateralClaimable(
      stakingId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    listingOffer(
      listingId: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    maxCollateralEligibleForTokens(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    nftListingIds(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    nftStakingIds(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    offerForNotListedToken(
      collectionId: BigNumberish,
      tokenId: BigNumberish,
      tokenContract: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    payPremium(
      stakingId: BigNumberish,
      isToken: boolean,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    paymentsDue(
      stakingId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    platform(overrides?: CallOverrides): Promise<BigNumber>;

    quoteForStakingExternal(
      tokenContract: string,
      tokenId: BigNumberish,
      collateralWei: BigNumberish,
      premiumWei: BigNumberish,
      deadlineUTC: BigNumberish,
      isTokenFee: boolean,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    removeStakingOffer(
      stakingId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    rentNFT(
      stakingId: BigNumberish,
      isTokenFee: boolean,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    stakingOffer(
      stakingId: BigNumberish,
      _collateral: BigNumberish,
      _premium: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    stopRental(
      stakingId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    stopStaking(
      stakingIndex: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    tokensDistributionAmount(overrides?: CallOverrides): Promise<BigNumber>;

    tokensDistributionEnd(overrides?: CallOverrides): Promise<BigNumber>;

    undasToken(overrides?: CallOverrides): Promise<BigNumber>;

    wETH(overrides?: CallOverrides): Promise<BigNumber>;

    whiteListNFTToggle(
      nft: string,
      whitelist: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    NFTTokenDistributionWhiteLister(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    NFTsEligibleForTokenDistribution(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    _listings(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    _listingsLastIndex(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    _offerLastIndex(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    _stakings(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    _stakingsExtension(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    _stakingsLastIndex(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    acceptListingOffer(
      listingId: BigNumberish,
      taker: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    acceptOfferForNotListedToken(
      offerId: BigNumberish,
      tokenContract: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    acceptStakingOffer(
      stakingId: BigNumberish,
      taker: string,
      isTokenFee: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    bidAndStake(
      tokenContract: string,
      tokenId: BigNumberish,
      collateralWei: BigNumberish,
      premiumWei: BigNumberish,
      deadlineUTC: BigNumberish,
      priceWei: BigNumberish,
      isTokenFee: boolean,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    bidExternal(
      tokenContract: string,
      tokenId: BigNumberish,
      priceWei: BigNumberish,
      isTokenFee: boolean,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    buyToken(
      listingId: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    canRentNFT(
      stakingId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    cancel(
      listingId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    cancelListingOffer(
      listingId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    cancelOfferForNotListedToken(
      offerId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    cancelStakingOffer(
      listingId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    claimCollateral(
      stakingId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    claimTokensListing(
      id: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    claimTokensRent(
      id: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    dateOfNextPayment(
      stakingId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    denyOfferForNotListedToken(
      offerId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    factory(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getContractBalanceV2(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getListing(
      listingId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getStaking(
      stakingId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    initialize(
      _platform: string,
      _token: string,
      _NFTTokenDistributionWhiteLister: string,
      _tokensDistributionAmount: BigNumberish,
      _maxCollateralEligibleForTokens: BigNumberish,
      _factory: string,
      _wETH: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    isBuyable(
      listingId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isCollateralClaimable(
      stakingId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    listingOffer(
      listingId: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    maxCollateralEligibleForTokens(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    nftListingIds(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    nftStakingIds(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    offerForNotListedToken(
      collectionId: BigNumberish,
      tokenId: BigNumberish,
      tokenContract: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    payPremium(
      stakingId: BigNumberish,
      isToken: boolean,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    paymentsDue(
      stakingId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    platform(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    quoteForStakingExternal(
      tokenContract: string,
      tokenId: BigNumberish,
      collateralWei: BigNumberish,
      premiumWei: BigNumberish,
      deadlineUTC: BigNumberish,
      isTokenFee: boolean,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    removeStakingOffer(
      stakingId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    rentNFT(
      stakingId: BigNumberish,
      isTokenFee: boolean,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    stakingOffer(
      stakingId: BigNumberish,
      _collateral: BigNumberish,
      _premium: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    stopRental(
      stakingId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    stopStaking(
      stakingIndex: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    tokensDistributionAmount(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    tokensDistributionEnd(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    undasToken(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    wETH(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    whiteListNFTToggle(
      nft: string,
      whitelist: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
