export { default as InfoSection } from '../page-components/InfoSection/InfoSection'
export { default as BrowseCategory } from '../page-components/BrowseCategory/BrowseCategory'
export { default as TopCollections } from '../page-components/TopCollections/TopCollections'
export { default as TopBuyers } from '../page-components/TopBuyers/TopBuyers'
export { default as RentNFT } from '../page-components/RentNFT/RentNFT'
