export { default as InfoSection } from './InfoSection/InfoSection'
export { default as BrowseCategory } from './BrowseCategory/BrowseCategory'
export { default as TopCollections } from './TopCollections/TopCollections'
export { default as TopBuyers } from './TopBuyers/TopBuyers'
export { default as RentNFT } from './RentNFT/RentNFT'
